# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2

defaults: &defaults
  working_directory: ~/next-boilerplate
  docker:
    - image: circleci/node:stretch

setupGit: &setupGit
  run: |
    git config user.email "$GIT_EMAIL" &&
    git config user.name "$GIT_USERNAME"

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Lint code
          command: npm run lint

      - run:
          name: Run unit tests
          command: npm test

      - run:
          name: Run build
          command: npm run build

      - persist_to_workspace:
          root: ./
          paths:
            - .next

  deploy:
    <<: *defaults
    steps:
      - checkout

      - attach_workspace:
          at: ./

      - <<: *setupGit

      - run:
          name: Force commit build dir
          command: |
            git add --force ./.next &&
            git commit -m "#$CIRCLE_BUILD_NUM release"

      - run:
          name: Deploy to Heroku
          command: git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

  greenkeeperUpdateLockFile:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Update package-lock.json
          command: npm install

      - <<: *setupGit

      - run:
          name: Commit lockfile if changed
          command: |
            if ! git diff-index --quiet HEAD --; then
              git add package-lock.json &&
              git commit -m "Updated lockfile to match Greenkeeper changes" &&
              export URL=$(echo $CIRCLE_REPOSITORY_URL | cut -c 4-) &&
              git remote add gk-origin https://${GH_TOKEN}:x-oauth-basic${URL} &&
              git push gk-origin HEAD:$CIRCLE_BRANCH
            fi

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - build
      - greenkeeperUpdateLockFile:
          filters:
            branches:
              only: /^greenkeeper\/.*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
