# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2

defaults: &defaults
  working_directory: ~/next-boilerplate
  docker:
    - image: circleci/node:stretch

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

  test:
    <<: *defaults
    steps:
      - run:
          name: Lint code
          command: npm run lint

      - run:
          name: Run unit tests
          command: npm test

  build:
    <<: *defaults
    steps:
      - run:
          name: Run build
          command: npm run build

  deploy:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: Deploy to Heroku
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
