# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2

defaults: &defaults
  working_directory: ~/next-boilerplate
  docker:
    - image: circleci/node:stretch

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Lint code
          command: npm run lint

      - run:
          name: Run unit tests
          command: npm test

      - run:
          name: Run build
          command: npm run build

      - persist_to_workspace:
          root: ./
          paths:
            - .next

  deploy:
    <<: *defaults
    steps:
      - checkout

      - attach_workspace:
          at: ./

      - run:
          name: Force commit build dir
          command: |
            git config user.email "$GIT_EMAIL" &&
            git config user.name "$GIT_USERNAME" &&
            git add --force ./.next &&
            git commit -m "#$CIRCLE_BUILD_NUM release"

      - run:
          name: Deploy to Heroku
          command: git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

  greenkeeperSetup:
    <<: *defaults
    steps:
      - run: npm install -g greenkeeper-lockfile

      - run: greenkeeper-lockfile-update

      - persist_to_workspace:
          root: ./
          paths:
            - .git

  greenkeeperUpdate:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./

      - run:
          name: SSH Avoid hosts unknown
          command: 'mkdir -p ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config'

      - run: greenkeeper-lockfile-upload

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - greenkeeperSetup:
          filters:
            branches:
              only: /^greenkeeper\/.*/
      - build
      - greenkeeperUpdate:
          requires:
            - greenkeeperSetup
            - build
          filters:
            branches:
              only: /^greenkeeper\/.*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
