# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults:
  working_directory: ~/next-boilerplate
  docker:
    - image: circleci/node:stretch

jobs:
  build:
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      # lint
      - run:
        name: Lint
        command: npm run lint
      # tests
      - run:
        name: Test
        command: npm test
      # build
      - run:
        name: Build
        command: npm run build

  deploy:
    steps:
      - checkout
      - run:
        name: Deploy
        command: |
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
